### ISSUE TITLE
No way to configure user/group settings

### ISSUE THREAD

**Issue by blkqi** [realies/soulseek-docker#5]
It would be great if there was a way to configure the user/group ID's so that writes would have the correct permissions on mapped volumes. Suggest sticking with the convention of passing `-e PGID=<gid> -e PUID=<uid>` to docker.

**Comment by realies** [comment]
Feel free to link to an example configuration or issue a pull request.

**Comment by xthursdayx** [comment]
+1

**Comment by realies** [comment]
Adding another user to run the app and have a configurable UID/GID would break the container configuration (mounted folders) for existing users that update. Any suggestions to go around that?

**Comment by blkqi** [comment]
Default PID/GID to 0 in Dockerfile. Later check /etc/passwd for an existing user (e.g. root) with those ID's. If one doesn't exist create a new one with a generic name. 

Not the cleanest example, but the general idea is sound: https://github.com/coppit/docker-inotify-command/blob/master/runas.sh

I should apologize... I would be more useful if I could, but this docker stuff is still new to me.

**Comment by realies** [comment]
That logic would also have to reconfigure the supervisor configuration based on the active user.

**Comment by Djeremaille** [comment]
:+1:

**Comment by bryab** [comment]
I have implemented this in my fork.  But it required me to change the paths from /root to a new folder, which i named /slsk.  Let me know if you all have any advice here, but this works for me.  You must set both PUID and PGID environment variables.

https://github.com/bryab/soulseek-docker/commit/f586ccef8a51c4338879b7b8079bd186b5387585

**Comment by realies** [comment]
@bryab, what a strange coincidence :)

**Comment by apurvis** [comment]
having an issue where the container is working great but doesn't seem to respect `PUID` and `PGID` when writing files.  my env vars are:
```
PUID=1027
PGID=100
UMASK=0002
```

from a shell inside the container files appear to be owned by `root` and also have no permissions.  
```
---------- 1 root root 1782057 May 19 03:23 '02 citys of refuge.mp3'
```

this is odd because the `init.sh` script did manage to create a `soulseek` user in `etc/passwd` in the container:
```
soulseek:x:1027:100::/data:/bin/false
```

but in the end that's not a huge deal to me... what is kind of a big deal to me is that from a terminal on _the machine_ files appear to be owned by root and have _all_ permissions:
```
-rwxrwxrwx+ 1 root root 150274770 May 18 22:51 'SHXCXCHCXSH - XLR8R Podcast 574, 201901.mp3'
```

giving execute permission to files written to the machine from a file sharing network is... alarming, let's say.

am i doing something stupid or is there a legitimate issue here?  

FWIW i am running this docker image inside [synology's docker app](https://www.synology.com/en-global/dsm/packages/Docker)
